export const SET_URL_NAME = "SET_URL_NAME";
export const SET_EVENT_ID = "SET_EVENT_ID";
export const SET_GROUPS = "SET_GROUPS";
export const SET_EVENTS = "SET_EVENTS";
export const SET_ATTENDANCE_LIST = "SET_ATTENDANCE_LIST";
export const SET_SIZE_ROULETTE = "SET_SIZE_ROULETTE";
export const SET_STATUS_MESSAGE = "SET_STATUS_MESSAGE";
export const SET_LOADING = "SET_LOADING";

export const SET_INDEX_ROULETTE = "SET_INDEX_ROULETTE";

export const SET_RUNNING_TIME = "SET_RUNNING_TIME";
export const SET_SUSPENSE_TIME = "SET_SUSPENSE_TIME";
export const SET_SUSPENSE = "SET_SUSPENSE";
export const SET_INDEX_WINNER = "SET_INDEX_WINNER";
export const SET_WINNER = "SET_WINNER";
export const SET_END_GAME = "SET_END_GAME";
export const SET_ROULETTE = "SET_ROULETTE";
